#!/bin/sh

## ┌┐ ┌─┐┌─┐┬ ┬┌┬┐
## ├┴┐└─┐├─┘││││││
## └─┘└─┘┴  └┴┘┴ ┴

# source file from currentdir/topdir down
#source $(dirname $0)/config

xrandr --mode 1920x1080
sxhkd &
compton &
bash ~/bin/bar.sh
dunst &
conky &
urxvtd -q -o -f

bspc config border_width            0
bspc config window_gap              8

bspc config split_ratio          0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config history_aware_focus     true
#bspc config adaptive raise          true

#bspc desktop I --layout monocle

bspc config pointer_modifier mod4
bspc config pointer_action2 move
bspc config pointer_action1 resize_corner
bspc config pointer_action3 resize_side

#bspc rule -a XTerm desktop='^2'
#bspc rule -a Gimp desktop='^5' state=floating follow=on
#bspc config focus_follows_pointer true

bspc monitor -d ㆀ ㆁ ㆂ  ㆃ ㆄ ㆅ ㆆ ㆇ ㆈ ㆉ

bspc rule -a mpv follow=off state=floating

xrdb -merge ~/.Xresources

# adapt to your own terminator emulator
bspc rule -a scratchpad sticky=on state=floating hidden=on
urxvt -name scratchpad -e ~/bin/scratch &
